package netdns

import (
	"context"
	"net"
	"testing"
	"time"
)

func TestIsLoopback(t *testing.T) {
	tests := []struct {
		addr string
		want bool
	}{
		{"127.0.0.1:53", true},
		{"127.0.0.53:53", true},
		{"127.1.2.3:53", true},
		{"[::1]:53", true},
		{"::1", true},
		{"127.0.0.1", true},
		{"localhost:53", true},
		{"localhost", true},
		{"8.8.8.8:53", false},
		{"1.1.1.1:53", false},
		{"9.9.9.9:53", false},
		{"192.168.1.1:53", false},
		{"10.0.0.1:53", false},
	}

	for _, tc := range tests {
		got := IsLoopback(tc.addr)
		if got != tc.want {
			t.Errorf("IsLoopback(%q) = %v; want %v", tc.addr, got, tc.want)
		}
	}
}

func TestParseResolvConf(t *testing.T) {
	sample := `
# Generated by NetworkManager
# Comment line
nameserver 1.1.1.1
nameserver 8.8.8.8:53
nameserver 2001:4860:4860::8888
; Another comment
`
	servers := parseResolvConf(sample)
	if len(servers) != 3 {
		t.Fatalf("expected 3 servers, got %d: %v", len(servers), servers)
	}
	if servers[0] != "1.1.1.1:53" {
		t.Errorf("expected servers[0] == '1.1.1.1:53', got %q", servers[0])
	}
	if servers[1] != "8.8.8.8:53" {
		t.Errorf("expected servers[1] == '8.8.8.8:53', got %q", servers[1])
	}
	if servers[2] != "[2001:4860:4860::8888]:53" {
		t.Errorf("expected servers[2] == '[2001:4860:4860::8888]:53', got %q", servers[2])
	}
}

func TestBuildCandidateList_DeadLoopback(t *testing.T) {
	defer ResetLoopbackProbe()
	SetLoopbackState(false) // simulate Android/Termux without loopback DNS

	list := BuildCandidateList("[::1]:53")
	if len(list) == 0 {
		t.Fatal("candidate list must not be empty")
	}

	// First server should NOT be [::1]:53
	if list[0] == "[::1]:53" || list[0] == "127.0.0.1:53" {
		t.Errorf("dead loopback must not be prioritized, got first candidate: %s", list[0])
	}

	// Should contain standard fallbacks
	hasCloudflare := false
	hasGoogle := false
	for _, s := range list {
		if s == "1.1.1.1:53" {
			hasCloudflare = true
		}
		if s == "8.8.8.8:53" {
			hasGoogle = true
		}
	}
	if !hasCloudflare || !hasGoogle {
		t.Errorf("candidate list should contain public fallbacks, got: %v", list)
	}
}

func TestBuildCandidateList_AliveLoopback(t *testing.T) {
	defer ResetLoopbackProbe()
	SetLoopbackState(true) // simulate desktop with local systemd-resolved

	list := BuildCandidateList("127.0.0.53:53")
	if len(list) == 0 {
		t.Fatal("candidate list must not be empty")
	}
	if list[0] != "127.0.0.53:53" {
		t.Errorf("alive loopback should be prioritized as first candidate, got %s", list[0])
	}
}

func TestResilientResolver_LookupSuccess(t *testing.T) {
	// Verify that the resilient resolver successfully resolves hosts even if
	// loopback is dead (reproducing Android/Termux environment)
	defer ResetLoopbackProbe()
	SetLoopbackState(false)

	resolver := GetResolver()
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	ips, err := resolver.LookupHost(ctx, "api.commandcode.ai")
	if err != nil {
		t.Fatalf("resilient lookup for api.commandcode.ai failed: %v", err)
	}
	if len(ips) == 0 {
		t.Fatal("expected at least one IP address returned")
	}
	for _, ip := range ips {
		if parsed := net.ParseIP(ip); parsed == nil {
			t.Errorf("invalid IP returned: %s", ip)
		}
	}
}

func TestResilientDNSConn_FailoverSimulation(t *testing.T) {
	// Create a ResilientDNSConn with an initial unreachable loopback conn,
	// and verify it transparently fails over to 1.1.1.1:53
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	dialer := &net.Dialer{Timeout: 2 * time.Second}
	deadConn, err := dialer.DialContext(ctx, "udp", "127.0.0.1:53")
	if err != nil {
		t.Skip("skipping UDP dial simulation: OS refused initial UDP connect")
	}

	conn := &ResilientDNSConn{
		Conn:          deadConn,
		ctx:           ctx,
		network:       "udp",
		dialer:        dialer,
		fallbackAddrs: []string{"1.1.1.1:53", "8.8.8.8:53"},
	}
	defer conn.Close()

	_ = conn.SetDeadline(time.Now().Add(3 * time.Second))

	// DNS query for example.com A record
	query := []byte{
		0xaa, 0xbb, 0x01, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
		0x07, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x03, 0x63, 0x6f, 0x6d, 0x00, 0x00, 0x01, 0x00, 0x01,
	}

	_, err = conn.Write(query)
	if err != nil {
		t.Fatalf("conn.Write failed: %v", err)
	}

	buf := make([]byte, 512)
	n, err := conn.Read(buf)
	if err != nil {
		t.Fatalf("conn.Read failover failed: %v", err)
	}
	if n < 12 {
		t.Fatalf("DNS response too short: %d bytes", n)
	}
}
